apiVersion: v1
kind: ConfigMap

metadata:
  name: configmap-api-front
  namespace: {{ .Release.Namespace }}

data:
  {{- range $name, $value := .Values.apiFront.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}