apiVersion: v1
kind: Service

metadata:
  name: redis
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}