apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Release.Namespace }}
data:
  {{- range $name, $value := .Values.postgres.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
