apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-collect
  namespace: demo-project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-collect
  template:
    metadata:
      labels:
        app: api-collect
    spec:
      restartPolicy: Always
      automountServiceAccountToken: false
      containers:
      - name: api-collect
        image: ghcr.io/remiv1/emsc-api-collect:1.0.0
        envFrom:
          - configMapRef:
              name: configmap-api-common
        env:
          - name: REDIS_WORKER_USERNAME
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: REDIS_WORKER_USERNAME
          - name: REDIS_WORKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: REDIS_WORKER_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
            ephemeral-storage: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
            ephemeral-storage: "512Mi"