apiVersion: v1
kind: ConfigMap

metadata:
  name: api-worker-config
  namespace: {{ .Release.Namespace }}

data:
  {{- range $name, $value := .Values.apiWorker.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  worker.conf: |
    {{- .Values.apiWorker.config | nindent 4 }}