apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: src-database--env-postgres
          image: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: db-main
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
