apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: src-redis--env-redis
          image: redis
          livenessProbe:
            exec:
              command:
                - redis-cli --user application --pass "${REDIS_APPLICATION_PASSWORD}" PING | grep -q PONG
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: redis-streams
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
