"""first migration

Revision ID: 35be609db105
Revises: 
Create Date: 2026-09-28 16:12:49.673349
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = '35be609db105'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Appliquer la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emsc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment="Identifiant unique de l'enregistrement"),
    sa.Column('ext_id', sa.String(), nullable=False, comment="Identifiant externe de l'enregistrement"),
    sa.Column('initial_datetime', sa.DateTime(), nullable=False, comment="Date et heure initiale de l'événement"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ext_id'),
    schema='app_schema'
    )
    op.create_table('geographic_zone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique de la zone géographique'),
    sa.Column('kind', sa.String(), nullable=False, comment='Type de la zone géographique (pays, continent, océan)'),
    sa.Column('code', sa.String(), nullable=False, comment='Code unique de la zone géographique'),
    sa.Column('name', sa.String(), nullable=False, comment='Nom de la zone géographique'),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='Limite géographique de la zone'),
    sa.CheckConstraint("kind IN ('country', 'continent', 'ocean')", name='zone_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='app_schema'
    )
    op.create_index('ix_geographic_zone_boundary', 'geographic_zone', ['boundary'], unique=False, schema='app_schema', postgresql_using='gist')
    op.create_table('emsc_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment="Identifiant unique de l'enregistrement"),
    sa.Column('emsc_id', sa.Integer(), nullable=False, comment="Identifiant de l'enregistrement EMSC associé"),
    sa.Column('magnitude', sa.Float(), nullable=False, comment="Magnitude de l'événement"),
    sa.Column('location', sa.String(), nullable=False, comment="Localisation de l'événement"),
    sa.Column('longitude', sa.Float(), nullable=False, comment="Longitude de l'événement"),
    sa.Column('latitude', sa.Float(), nullable=False, comment="Latitude de l'événement"),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), sa.Computed('ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)', persisted=True), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False, comment="Profondeur de l'événement"),
    sa.Column('additional_data', sa.JSON(), nullable=True, comment="Données supplémentaires de l'événement"),
    sa.Column('event_datetime', sa.DateTime(), nullable=False, comment="Date et heure de l'événement"),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='emsc_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='emsc_longitude'),
    sa.ForeignKeyConstraint(['emsc_id'], ['app_schema.emsc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emsc_id'),
    schema='app_schema'
    )
    op.create_index('ix_emsc_details_position', 'emsc_details', ['position'], unique=False, schema='app_schema', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annuler la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emsc_details_position', table_name='emsc_details', schema='app_schema', postgresql_using='gist')
    op.drop_table('emsc_details', schema='app_schema')
    op.drop_index('ix_geographic_zone_boundary', table_name='geographic_zone', schema='app_schema', postgresql_using='gist')
    op.drop_table('geographic_zone', schema='app_schema')
    op.drop_table('emsc', schema='app_schema')
    # ### end Alembic commands ###