"""first_migration

Revision ID: 39b76296f78c
Revises: 
Create Date: 2026-09-28 10:15:25.267840
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '39b76296f78c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Appliquer la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emsc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment="Identifiant unique de l'enregistrement"),
    sa.Column('ext_id', sa.String(), nullable=False, comment="Identifiant externe de l'enregistrement"),
    sa.Column('magnitude', sa.Float(), nullable=False, comment="Magnitude de l'événement"),
    sa.Column('location', sa.String(), nullable=False, comment="Localisation de l'événement"),
    sa.Column('additional_data', sa.JSON(), nullable=True, comment="Données supplémentaires de l'événement"),
    sa.PrimaryKeyConstraint('id'),
    schema='app_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annuler la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emsc', schema='app_schema')
    # ### end Alembic commands ###