apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-data
  namespace: demo-project

spec:
  # stockage local k3s
  storageClassName: local-path
  
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi
