apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: api-back
  namespace: demo-project

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-back
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 66